//! Render the proxy contracts to markdown for the docs site.
//!
//! Driver authors read generated docs, not the TOML, and the two cannot drift because there
//! is only one source. This lives beside the contracts rather than in the controller for the
//! same reason they do: rendering a contract needs the contract and nothing else, and a
//! renderer in a private repository could only ever be run by us.
//!
//! `junodrv docs` writes the result; the workflow that runs it on a contract change is what
//! makes the docs repo's copy generated rather than maintained.

use super::{Param, Proxy, ProxyRegistry, Signature, ValueType};
use std::collections::BTreeMap;
use std::fmt::Write;

const BANNER: &str = "<!-- Generated by `junodrv docs` from proxies/. Do not edit by hand. -->";

fn ty(t: ValueType) -> &'static str {
    match t {
        ValueType::Bool => "bool",
        ValueType::U8 => "u8",
        ValueType::U32 => "u32",
        ValueType::I32 => "i32",
        ValueType::F32 => "f32",
        ValueType::String => "string",
        ValueType::StringList => "string[]",
        ValueType::Bytes => "bytes",
    }
}

fn param_cell(p: &Param) -> String {
    let mut s = format!("`{}`", ty(p.ty));
    if !p.values.is_empty() {
        s = format!(
            "one of {}",
            p.values
                .iter()
                .map(|v| format!("`{v}`"))
                .collect::<Vec<_>>()
                .join(" · ")
        );
    } else {
        match (p.min, p.max) {
            (Some(lo), Some(hi)) => s.push_str(&format!(" {lo}–{hi}")),
            (Some(lo), None) => s.push_str(&format!(" ≥{lo}")),
            (None, Some(hi)) => s.push_str(&format!(" ≤{hi}")),
            (None, None) => {}
        }
    }
    if p.optional {
        s.push_str(" *(optional)*");
    }
    s
}

fn signatures(out: &mut String, heading: &str, sigs: &BTreeMap<String, Signature>) {
    if sigs.is_empty() {
        return;
    }
    let _ = writeln!(out, "\n## {heading}\n");
    for (name, sig) in sigs {
        let _ = write!(out, "### `{name}`\n\n");
        if let Some(req) = &sig.requires {
            let _ = writeln!(out, "> Only present when `{req}` is declared true.\n");
        }
        if !sig.doc.is_empty() {
            let _ = writeln!(out, "{}\n", sig.doc);
        }
        if sig.params.is_empty() {
            let _ = writeln!(out, "No parameters.\n");
        } else {
            let _ = writeln!(out, "| Parameter | Type | Notes |");
            let _ = writeln!(out, "| --- | --- | --- |");
            for (pname, p) in &sig.params {
                let _ = writeln!(out, "| `{pname}` | {} | {} |", param_cell(p), p.doc);
            }
            let _ = writeln!(out);
        }
    }
}

pub fn render(p: &Proxy) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{BANNER}\n");
    let _ = writeln!(out, "# {} — `{}` v{}\n", p.title, p.name, p.version);
    if !p.description.is_empty() {
        let _ = writeln!(out, "{}\n", p.description.trim());
    }

    if !p.capabilities.is_empty() {
        let _ = writeln!(out, "## Capabilities\n");
        let _ = writeln!(
            out,
            "Declared in the driver manifest under `[[proxy]] capabilities`. Anything not \
             declared takes the default below.\n"
        );
        let _ = writeln!(out, "| Capability | Type | Default | Meaning |");
        let _ = writeln!(out, "| --- | --- | --- | --- |");
        for (name, c) in &p.capabilities {
            let _ = writeln!(
                out,
                "| `{name}` | `{}` | `{}` | {} |",
                ty(c.ty),
                c.default,
                c.doc
            );
        }
    }

    signatures(&mut out, "Commands", &p.commands);
    signatures(&mut out, "Notifications", &p.notifications);

    if !p.state.is_empty() {
        let _ = writeln!(out, "\n## State\n");
        let _ = writeln!(
            out,
            "Last-known values core keeps for a binding of this proxy.\n"
        );
        let _ = writeln!(out, "| Key | Type | Meaning |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for (name, s) in &p.state {
            let _ = writeln!(out, "| `{name}` | `{}` | {} |", ty(s.ty), s.doc);
        }
    }
    out
}

pub fn render_index(reg: &ProxyRegistry) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{BANNER}\n");
    let _ = writeln!(out, "# Proxy Reference\n");
    let _ = writeln!(
        out,
        "Every device class Juno understands. A driver implements one or more of these and \
         declares which capabilities it supports; core computes the callable command set from \
         that.\n"
    );

    let mut by_cat: BTreeMap<&str, Vec<&Proxy>> = BTreeMap::new();
    for p in reg.iter() {
        by_cat.entry(p.category.as_str()).or_default().push(p);
    }
    for (cat, list) in by_cat {
        let title = match cat {
            "connection" => "Connection proxies — relays, contacts, IR, serial",
            "av" => "AV",
            "lighting" => "Lighting",
            "environment" => "Environment",
            "security" => "Security",
            "system" => "System",
            other => other,
        };
        let _ = writeln!(out, "## {title}\n");
        let _ = writeln!(out, "| Proxy | Title | Commands |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for p in list {
            let _ = writeln!(
                out,
                "| [`{}`]({}.md) | {} | {} |",
                p.name,
                p.name,
                p.title,
                p.commands.len()
            );
        }
        let _ = writeln!(out);
    }
    out
}

/// Files that `docs/proxies/` should contain, as (relative path, contents).
pub fn all(reg: &ProxyRegistry) -> Vec<(String, String)> {
    let mut files: Vec<_> = reg
        .iter()
        .map(|p| (format!("{}.md", p.name), render(p)))
        .collect();
    files.push(("README.md".into(), render_index(reg)));
    files
}
